-- Real SEC filings ingested on 2026-08-07T00:11:02.915Z
-- Generated by Hidden Catalyst ingestion pipeline

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000001750_000114036126031084', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000001750', '2026-08-04', NOW(), 'sec_0000001750_000114036126031084', 'Form ARS — AAR CORP', 'AAR CORP (AIR). Form ARS. Date 2026-08-04', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000001750_000114036126031084', 'doc_sec_0000001750_000114036126031084', 'AIR: ARS filed 2026-08-04', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000001750_000114036126031084', 'sec_0000001750', 'Form ARS — AAR CORP', 'AAR CORP (AIR). Form ARS. Date 2026-08-04', 'candidate', '2026-08-04', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000001750_000114036126031084', 'opp_sec_0000001750_000114036126031084', 'verified_fact', 'AIR: filed ARS on 2026-08-04', 0.9, '["ev_sec_0000001750_000114036126031084"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000001750_000114036126031084', 'opp_sec_0000001750_000114036126031084', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000001750_000114036126031080', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000001750', '2026-08-04', NOW(), 'sec_0000001750_000114036126031080', 'Form DEFA14A — AAR CORP', 'AAR CORP (AIR). Form DEFA14A. Date 2026-08-04', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000001750_000114036126031080', 'doc_sec_0000001750_000114036126031080', 'AIR: DEFA14A filed 2026-08-04', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000001750_000114036126031080', 'sec_0000001750', 'Form DEFA14A — AAR CORP', 'AAR CORP (AIR). Form DEFA14A. Date 2026-08-04', 'candidate', '2026-08-04', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000001750_000114036126031080', 'opp_sec_0000001750_000114036126031080', 'verified_fact', 'AIR: filed DEFA14A on 2026-08-04', 0.9, '["ev_sec_0000001750_000114036126031080"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000001750_000114036126031080', 'opp_sec_0000001750_000114036126031080', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000001750_000114036126031078', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000001750', '2026-08-04', NOW(), 'sec_0000001750_000114036126031078', 'Form DEF 14A — AAR CORP', 'AAR CORP (AIR). Form DEF 14A. Date 2026-08-04', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000001750_000114036126031078', 'doc_sec_0000001750_000114036126031078', 'AIR: DEF 14A filed 2026-08-04', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000001750_000114036126031078', 'sec_0000001750', 'Form DEF 14A — AAR CORP', 'AAR CORP (AIR). Form DEF 14A. Date 2026-08-04', 'candidate', '2026-08-04', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000001750_000114036126031078', 'opp_sec_0000001750_000114036126031078', 'verified_fact', 'AIR: filed DEF 14A on 2026-08-04', 0.9, '["ev_sec_0000001750_000114036126031078"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000001750_000114036126031078', 'opp_sec_0000001750_000114036126031078', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000001800_000162828026050134', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000001800', '2026-07-28', NOW(), 'sec_0000001800_000162828026050134', 'Form 10-Q — ABBOTT LABORATORIES', 'ABBOTT LABORATORIES (ABT). Form 10-Q. Date 2026-07-28', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000001800_000162828026050134', 'doc_sec_0000001800_000162828026050134', 'ABT: 10-Q filed 2026-07-28', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000001800_000162828026050134', 'sec_0000001800', 'Form 10-Q — ABBOTT LABORATORIES', 'ABBOTT LABORATORIES (ABT). Form 10-Q. Date 2026-07-28', 'candidate', '2026-07-28', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000001800_000162828026050134', 'opp_sec_0000001800_000162828026050134', 'verified_fact', 'ABT: filed 10-Q on 2026-07-28', 0.9, '["ev_sec_0000001800_000162828026050134"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000001800_000162828026050134', 'opp_sec_0000001800_000162828026050134', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000001800_000162828026048377', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000001800', '2026-07-16', NOW(), 'sec_0000001800_000162828026048377', 'Form 8-K — ABBOTT LABORATORIES', 'ABBOTT LABORATORIES (ABT). Form 8-K. Date 2026-07-16', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000001800_000162828026048377', 'doc_sec_0000001800_000162828026048377', 'ABT: 8-K filed 2026-07-16', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000001800_000162828026048377', 'sec_0000001800', 'Form 8-K — ABBOTT LABORATORIES', 'ABBOTT LABORATORIES (ABT). Form 8-K. Date 2026-07-16', 'candidate', '2026-07-16', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000001800_000162828026048377', 'opp_sec_0000001800_000162828026048377', 'verified_fact', 'ABT: filed 8-K on 2026-07-16', 0.9, '["ev_sec_0000001800_000162828026048377"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000001800_000162828026048377', 'opp_sec_0000001800_000162828026048377', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002098_000119312526338211', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002098', '2026-08-06', NOW(), 'sec_0000002098_000119312526338211', 'Form 10-Q — ACME UNITED CORP', 'ACME UNITED CORP (ACU). Form 10-Q. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002098_000119312526338211', 'doc_sec_0000002098_000119312526338211', 'ACU: 10-Q filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002098_000119312526338211', 'sec_0000002098', 'Form 10-Q — ACME UNITED CORP', 'ACME UNITED CORP (ACU). Form 10-Q. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002098_000119312526338211', 'opp_sec_0000002098_000119312526338211', 'verified_fact', 'ACU: filed 10-Q on 2026-08-06', 0.9, '["ev_sec_0000002098_000119312526338211"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002098_000119312526338211', 'opp_sec_0000002098_000119312526338211', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002098_000195917326005542', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002098', '2026-08-03', NOW(), 'sec_0000002098_000195917326005542', 'Form 144 — ACME UNITED CORP', 'ACME UNITED CORP (ACU). Form 144. Date 2026-08-03', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002098_000195917326005542', 'doc_sec_0000002098_000195917326005542', 'ACU: 144 filed 2026-08-03', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002098_000195917326005542', 'sec_0000002098', 'Form 144 — ACME UNITED CORP', 'ACME UNITED CORP (ACU). Form 144. Date 2026-08-03', 'candidate', '2026-08-03', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002098_000195917326005542', 'opp_sec_0000002098_000195917326005542', 'verified_fact', 'ACU: filed 144 on 2026-08-03', 0.9, '["ev_sec_0000002098_000195917326005542"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002098_000195917326005542', 'opp_sec_0000002098_000195917326005542', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002186_000143774926021150', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002186', '2026-06-18', NOW(), 'sec_0000002186_000143774926021150', 'Form 3 — BK Technologies Corp', 'BK Technologies Corp (BKTI). Form 3. Date 2026-06-18', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002186_000143774926021150', 'doc_sec_0000002186_000143774926021150', 'BKTI: 3 filed 2026-06-18', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002186_000143774926021150', 'sec_0000002186', 'Form 3 — BK Technologies Corp', 'BK Technologies Corp (BKTI). Form 3. Date 2026-06-18', 'candidate', '2026-06-18', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002186_000143774926021150', 'opp_sec_0000002186_000143774926021150', 'verified_fact', 'BKTI: filed 3 on 2026-06-18', 0.9, '["ev_sec_0000002186_000143774926021150"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002186_000143774926021150', 'opp_sec_0000002186_000143774926021150', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002186_000143774926021148', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002186', '2026-06-18', NOW(), 'sec_0000002186_000143774926021148', 'Form 8-K — BK Technologies Corp', 'BK Technologies Corp (BKTI). Form 8-K. Date 2026-06-18', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002186_000143774926021148', 'doc_sec_0000002186_000143774926021148', 'BKTI: 8-K filed 2026-06-18', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002186_000143774926021148', 'sec_0000002186', 'Form 8-K — BK Technologies Corp', 'BK Technologies Corp (BKTI). Form 8-K. Date 2026-06-18', 'candidate', '2026-06-18', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002186_000143774926021148', 'opp_sec_0000002186_000143774926021148', 'verified_fact', 'BKTI: filed 8-K on 2026-06-18', 0.9, '["ev_sec_0000002186_000143774926021148"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002186_000143774926021148', 'opp_sec_0000002186_000143774926021148', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002186_000195917326004741', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002186', '2026-06-17', NOW(), 'sec_0000002186_000195917326004741', 'Form 144/A — BK Technologies Corp', 'BK Technologies Corp (BKTI). Form 144/A. Date 2026-06-17', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002186_000195917326004741', 'doc_sec_0000002186_000195917326004741', 'BKTI: 144/A filed 2026-06-17', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002186_000195917326004741', 'sec_0000002186', 'Form 144/A — BK Technologies Corp', 'BK Technologies Corp (BKTI). Form 144/A. Date 2026-06-17', 'candidate', '2026-06-17', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002186_000195917326004741', 'opp_sec_0000002186_000195917326004741', 'verified_fact', 'BKTI: filed 144/A on 2026-06-17', 0.9, '["ev_sec_0000002186_000195917326004741"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002186_000195917326004741', 'opp_sec_0000002186_000195917326004741', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002230_000110465926088330', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002230', '2026-07-30', NOW(), 'sec_0000002230_000110465926088330', 'Form N-CSRS — ADAMS DIVERSIFIED EQUITY FUND, INC.', 'ADAMS DIVERSIFIED EQUITY FUND, INC. (ADX). Form N-CSRS. Date 2026-07-30', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002230_000110465926088330', 'doc_sec_0000002230_000110465926088330', 'ADX: N-CSRS filed 2026-07-30', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002230_000110465926088330', 'sec_0000002230', 'Form N-CSRS — ADAMS DIVERSIFIED EQUITY FUND, INC.', 'ADAMS DIVERSIFIED EQUITY FUND, INC. (ADX). Form N-CSRS. Date 2026-07-30', 'candidate', '2026-07-30', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002230_000110465926088330', 'opp_sec_0000002230_000110465926088330', 'verified_fact', 'ADX: filed N-CSRS on 2026-07-30', 0.9, '["ev_sec_0000002230_000110465926088330"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002230_000110465926088330', 'opp_sec_0000002230_000110465926088330', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002230_000110465926088189', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002230', '2026-07-29', NOW(), 'sec_0000002230_000110465926088189', 'Form NPORT-P — ADAMS DIVERSIFIED EQUITY FUND, INC.', 'ADAMS DIVERSIFIED EQUITY FUND, INC. (ADX). Form NPORT-P. Date 2026-07-29', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002230_000110465926088189', 'doc_sec_0000002230_000110465926088189', 'ADX: NPORT-P filed 2026-07-29', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002230_000110465926088189', 'sec_0000002230', 'Form NPORT-P — ADAMS DIVERSIFIED EQUITY FUND, INC.', 'ADAMS DIVERSIFIED EQUITY FUND, INC. (ADX). Form NPORT-P. Date 2026-07-29', 'candidate', '2026-07-29', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002230_000110465926088189', 'opp_sec_0000002230_000110465926088189', 'verified_fact', 'ADX: filed NPORT-P on 2026-07-29', 0.9, '["ev_sec_0000002230_000110465926088189"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002230_000110465926088189', 'opp_sec_0000002230_000110465926088189', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002230_000110465926088075', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002230', '2026-07-29', NOW(), 'sec_0000002230_000110465926088075', 'Form N-PX — ADAMS DIVERSIFIED EQUITY FUND, INC.', 'ADAMS DIVERSIFIED EQUITY FUND, INC. (ADX). Form N-PX. Date 2026-07-29', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002230_000110465926088075', 'doc_sec_0000002230_000110465926088075', 'ADX: N-PX filed 2026-07-29', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002230_000110465926088075', 'sec_0000002230', 'Form N-PX — ADAMS DIVERSIFIED EQUITY FUND, INC.', 'ADAMS DIVERSIFIED EQUITY FUND, INC. (ADX). Form N-PX. Date 2026-07-29', 'candidate', '2026-07-29', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002230_000110465926088075', 'opp_sec_0000002230_000110465926088075', 'verified_fact', 'ADX: filed N-PX on 2026-07-29', 0.9, '["ev_sec_0000002230_000110465926088075"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002230_000110465926088075', 'opp_sec_0000002230_000110465926088075', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002488_000000248826000123', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002488', '2026-08-05', NOW(), 'sec_0000002488_000000248826000123', 'Form 10-Q — ADVANCED MICRO DEVICES INC', 'ADVANCED MICRO DEVICES INC (AMD). Form 10-Q. Date 2026-08-05', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002488_000000248826000123', 'doc_sec_0000002488_000000248826000123', 'AMD: 10-Q filed 2026-08-05', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002488_000000248826000123', 'sec_0000002488', 'Form 10-Q — ADVANCED MICRO DEVICES INC', 'ADVANCED MICRO DEVICES INC (AMD). Form 10-Q. Date 2026-08-05', 'candidate', '2026-08-05', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002488_000000248826000123', 'opp_sec_0000002488_000000248826000123', 'verified_fact', 'AMD: filed 10-Q on 2026-08-05', 0.9, '["ev_sec_0000002488_000000248826000123"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002488_000000248826000123', 'opp_sec_0000002488_000000248826000123', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002488_000000248826000121', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002488', '2026-08-04', NOW(), 'sec_0000002488_000000248826000121', 'Form 8-K — ADVANCED MICRO DEVICES INC', 'ADVANCED MICRO DEVICES INC (AMD). Form 8-K. Date 2026-08-04', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002488_000000248826000121', 'doc_sec_0000002488_000000248826000121', 'AMD: 8-K filed 2026-08-04', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002488_000000248826000121', 'sec_0000002488', 'Form 8-K — ADVANCED MICRO DEVICES INC', 'ADVANCED MICRO DEVICES INC (AMD). Form 8-K. Date 2026-08-04', 'candidate', '2026-08-04', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002488_000000248826000121', 'opp_sec_0000002488_000000248826000121', 'verified_fact', 'AMD: filed 8-K on 2026-08-04', 0.9, '["ev_sec_0000002488_000000248826000121"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002488_000000248826000121', 'opp_sec_0000002488_000000248826000121', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002809_000110465926088794', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002809', '2026-07-30', NOW(), 'sec_0000002809_000110465926088794', 'Form 6-K — AGNICO EAGLE MINES LTD', 'AGNICO EAGLE MINES LTD (AEM). Form 6-K. Date 2026-07-30', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002809_000110465926088794', 'doc_sec_0000002809_000110465926088794', 'AEM: 6-K filed 2026-07-30', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002809_000110465926088794', 'sec_0000002809', 'Form 6-K — AGNICO EAGLE MINES LTD', 'AGNICO EAGLE MINES LTD (AEM). Form 6-K. Date 2026-07-30', 'candidate', '2026-07-30', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002809_000110465926088794', 'opp_sec_0000002809_000110465926088794', 'verified_fact', 'AEM: filed 6-K on 2026-07-30', 0.9, '["ev_sec_0000002809_000110465926088794"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002809_000110465926088794', 'opp_sec_0000002809_000110465926088794', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002809_000110465926088216', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002809', '2026-07-29', NOW(), 'sec_0000002809_000110465926088216', 'Form 6-K — AGNICO EAGLE MINES LTD', 'AGNICO EAGLE MINES LTD (AEM). Form 6-K. Date 2026-07-29', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002809_000110465926088216', 'doc_sec_0000002809_000110465926088216', 'AEM: 6-K filed 2026-07-29', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002809_000110465926088216', 'sec_0000002809', 'Form 6-K — AGNICO EAGLE MINES LTD', 'AGNICO EAGLE MINES LTD (AEM). Form 6-K. Date 2026-07-29', 'candidate', '2026-07-29', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002809_000110465926088216', 'opp_sec_0000002809_000110465926088216', 'verified_fact', 'AEM: filed 6-K on 2026-07-29', 0.9, '["ev_sec_0000002809_000110465926088216"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002809_000110465926088216', 'opp_sec_0000002809_000110465926088216', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002809_000110465926087022', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002809', '2026-07-27', NOW(), 'sec_0000002809_000110465926087022', 'Form 6-K — AGNICO EAGLE MINES LTD', 'AGNICO EAGLE MINES LTD (AEM). Form 6-K. Date 2026-07-27', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002809_000110465926087022', 'doc_sec_0000002809_000110465926087022', 'AEM: 6-K filed 2026-07-27', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002809_000110465926087022', 'sec_0000002809', 'Form 6-K — AGNICO EAGLE MINES LTD', 'AGNICO EAGLE MINES LTD (AEM). Form 6-K. Date 2026-07-27', 'candidate', '2026-07-27', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002809_000110465926087022', 'opp_sec_0000002809_000110465926087022', 'verified_fact', 'AEM: filed 6-K on 2026-07-27', 0.9, '["ev_sec_0000002809_000110465926087022"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002809_000110465926087022', 'opp_sec_0000002809_000110465926087022', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002969_000000296926000036', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002969', '2026-07-30', NOW(), 'sec_0000002969_000000296926000036', 'Form 10-Q — Air Products & Chemicals, Inc.', 'Air Products & Chemicals, Inc. (APD). Form 10-Q. Date 2026-07-30', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002969_000000296926000036', 'doc_sec_0000002969_000000296926000036', 'APD: 10-Q filed 2026-07-30', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002969_000000296926000036', 'sec_0000002969', 'Form 10-Q — Air Products & Chemicals, Inc.', 'Air Products & Chemicals, Inc. (APD). Form 10-Q. Date 2026-07-30', 'candidate', '2026-07-30', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002969_000000296926000036', 'opp_sec_0000002969_000000296926000036', 'verified_fact', 'APD: filed 10-Q on 2026-07-30', 0.9, '["ev_sec_0000002969_000000296926000036"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002969_000000296926000036', 'opp_sec_0000002969_000000296926000036', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000002969_000000296926000034', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000002969', '2026-07-30', NOW(), 'sec_0000002969_000000296926000034', 'Form 8-K — Air Products & Chemicals, Inc.', 'Air Products & Chemicals, Inc. (APD). Form 8-K. Date 2026-07-30', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000002969_000000296926000034', 'doc_sec_0000002969_000000296926000034', 'APD: 8-K filed 2026-07-30', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000002969_000000296926000034', 'sec_0000002969', 'Form 8-K — Air Products & Chemicals, Inc.', 'Air Products & Chemicals, Inc. (APD). Form 8-K. Date 2026-07-30', 'candidate', '2026-07-30', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000002969_000000296926000034', 'opp_sec_0000002969_000000296926000034', 'verified_fact', 'APD: filed 8-K on 2026-07-30', 0.9, '["ev_sec_0000002969_000000296926000034"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000002969_000000296926000034', 'opp_sec_0000002969_000000296926000034', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003124_000095010326011930', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003124', '2026-08-05', NOW(), 'sec_0000003124_000095010326011930', 'Form 425 — AKZO NOBEL NV', 'AKZO NOBEL NV (AKZOF). Form 425. Date 2026-08-05', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003124_000095010326011930', 'doc_sec_0000003124_000095010326011930', 'AKZOF: 425 filed 2026-08-05', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003124_000095010326011930', 'sec_0000003124', 'Form 425 — AKZO NOBEL NV', 'AKZO NOBEL NV (AKZOF). Form 425. Date 2026-08-05', 'candidate', '2026-08-05', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003124_000095010326011930', 'opp_sec_0000003124_000095010326011930', 'verified_fact', 'AKZOF: filed 425 on 2026-08-05', 0.9, '["ev_sec_0000003124_000095010326011930"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003124_000095010326011930', 'opp_sec_0000003124_000095010326011930', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003124_000119312526322163', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003124', '2026-07-29', NOW(), 'sec_0000003124_000119312526322163', 'Form 424B3 — AKZO NOBEL NV', 'AKZO NOBEL NV (AKZOF). Form 424B3. Date 2026-07-29', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003124_000119312526322163', 'doc_sec_0000003124_000119312526322163', 'AKZOF: 424B3 filed 2026-07-29', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003124_000119312526322163', 'sec_0000003124', 'Form 424B3 — AKZO NOBEL NV', 'AKZO NOBEL NV (AKZOF). Form 424B3. Date 2026-07-29', 'candidate', '2026-07-29', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003124_000119312526322163', 'opp_sec_0000003124_000119312526322163', 'verified_fact', 'AKZOF: filed 424B3 on 2026-07-29', 0.9, '["ev_sec_0000003124_000119312526322163"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003124_000119312526322163', 'opp_sec_0000003124_000119312526322163', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003124_000095010326011045', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003124', '2026-07-23', NOW(), 'sec_0000003124_000095010326011045', 'Form 6-K — AKZO NOBEL NV', 'AKZO NOBEL NV (AKZOF). Form 6-K. Date 2026-07-23', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003124_000095010326011045', 'doc_sec_0000003124_000095010326011045', 'AKZOF: 6-K filed 2026-07-23', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003124_000095010326011045', 'sec_0000003124', 'Form 6-K — AKZO NOBEL NV', 'AKZO NOBEL NV (AKZOF). Form 6-K. Date 2026-07-23', 'candidate', '2026-07-23', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003124_000095010326011045', 'opp_sec_0000003124_000095010326011045', 'verified_fact', 'AKZOF: filed 6-K on 2026-07-23', 0.9, '["ev_sec_0000003124_000095010326011045"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003124_000095010326011045', 'opp_sec_0000003124_000095010326011045', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003197_000031506626001976', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003197', '2026-08-06', NOW(), 'sec_0000003197_000031506626001976', 'Form SCHEDULE 13G/A — CECO ENVIRONMENTAL CORP', 'CECO ENVIRONMENTAL CORP (CECO). Form SCHEDULE 13G/A. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003197_000031506626001976', 'doc_sec_0000003197_000031506626001976', 'CECO: SCHEDULE 13G/A filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003197_000031506626001976', 'sec_0000003197', 'Form SCHEDULE 13G/A — CECO ENVIRONMENTAL CORP', 'CECO ENVIRONMENTAL CORP (CECO). Form SCHEDULE 13G/A. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003197_000031506626001976', 'opp_sec_0000003197_000031506626001976', 'verified_fact', 'CECO: filed SCHEDULE 13G/A on 2026-08-06', 0.9, '["ev_sec_0000003197_000031506626001976"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003197_000031506626001976', 'opp_sec_0000003197_000031506626001976', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003197_000110465926089307', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003197', '2026-08-03', NOW(), 'sec_0000003197_000110465926089307', 'Form 8-K/A — CECO ENVIRONMENTAL CORP', 'CECO ENVIRONMENTAL CORP (CECO). Form 8-K/A. Date 2026-08-03', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003197_000110465926089307', 'doc_sec_0000003197_000110465926089307', 'CECO: 8-K/A filed 2026-08-03', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003197_000110465926089307', 'sec_0000003197', 'Form 8-K/A — CECO ENVIRONMENTAL CORP', 'CECO ENVIRONMENTAL CORP (CECO). Form 8-K/A. Date 2026-08-03', 'candidate', '2026-08-03', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003197_000110465926089307', 'opp_sec_0000003197_000110465926089307', 'verified_fact', 'CECO: filed 8-K/A on 2026-08-03', 0.9, '["ev_sec_0000003197_000110465926089307"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003197_000110465926089307', 'opp_sec_0000003197_000110465926089307', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003453_000110465926090003', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003453', '2026-08-04', NOW(), 'sec_0000003453_000110465926090003', 'Form 10-Q — Matson, Inc.', 'Matson, Inc. (MATX). Form 10-Q. Date 2026-08-04', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003453_000110465926090003', 'doc_sec_0000003453_000110465926090003', 'MATX: 10-Q filed 2026-08-04', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003453_000110465926090003', 'sec_0000003453', 'Form 10-Q — Matson, Inc.', 'Matson, Inc. (MATX). Form 10-Q. Date 2026-08-04', 'candidate', '2026-08-04', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003453_000110465926090003', 'opp_sec_0000003453_000110465926090003', 'verified_fact', 'MATX: filed 10-Q on 2026-08-04', 0.9, '["ev_sec_0000003453_000110465926090003"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003453_000110465926090003', 'opp_sec_0000003453_000110465926090003', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003453_000110465926089794', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003453', '2026-08-03', NOW(), 'sec_0000003453_000110465926089794', 'Form 8-K — Matson, Inc.', 'Matson, Inc. (MATX). Form 8-K. Date 2026-08-03', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003453_000110465926089794', 'doc_sec_0000003453_000110465926089794', 'MATX: 8-K filed 2026-08-03', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003453_000110465926089794', 'sec_0000003453', 'Form 8-K — Matson, Inc.', 'Matson, Inc. (MATX). Form 8-K. Date 2026-08-03', 'candidate', '2026-08-03', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003453_000110465926089794', 'opp_sec_0000003453_000110465926089794', 'verified_fact', 'MATX: filed 8-K on 2026-08-03', 0.9, '["ev_sec_0000003453_000110465926089794"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003453_000110465926089794', 'opp_sec_0000003453_000110465926089794', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003453_000210011926001472', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003453', '2026-07-31', NOW(), 'sec_0000003453_000210011926001472', 'Form SCHEDULE 13G/A — Matson, Inc.', 'Matson, Inc. (MATX). Form SCHEDULE 13G/A. Date 2026-07-31', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003453_000210011926001472', 'doc_sec_0000003453_000210011926001472', 'MATX: SCHEDULE 13G/A filed 2026-07-31', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003453_000210011926001472', 'sec_0000003453', 'Form SCHEDULE 13G/A — Matson, Inc.', 'Matson, Inc. (MATX). Form SCHEDULE 13G/A. Date 2026-07-31', 'candidate', '2026-07-31', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003453_000210011926001472', 'opp_sec_0000003453_000210011926001472', 'verified_fact', 'MATX: filed SCHEDULE 13G/A on 2026-07-31', 0.9, '["ev_sec_0000003453_000210011926001472"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003453_000210011926001472', 'opp_sec_0000003453_000210011926001472', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003499_000000349926000038', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003499', '2026-08-03', NOW(), 'sec_0000003499_000000349926000038', 'Form 10-Q — ALEXANDERS INC', 'ALEXANDERS INC (ALX). Form 10-Q. Date 2026-08-03', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003499_000000349926000038', 'doc_sec_0000003499_000000349926000038', 'ALX: 10-Q filed 2026-08-03', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003499_000000349926000038', 'sec_0000003499', 'Form 10-Q — ALEXANDERS INC', 'ALEXANDERS INC (ALX). Form 10-Q. Date 2026-08-03', 'candidate', '2026-08-03', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003499_000000349926000038', 'opp_sec_0000003499_000000349926000038', 'verified_fact', 'ALX: filed 10-Q on 2026-08-03', 0.9, '["ev_sec_0000003499_000000349926000038"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003499_000000349926000038', 'opp_sec_0000003499_000000349926000038', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003499_000195004726005844', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003499', '2026-06-09', NOW(), 'sec_0000003499_000195004726005844', 'Form 144 — ALEXANDERS INC', 'ALEXANDERS INC (ALX). Form 144. Date 2026-06-09', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003499_000195004726005844', 'doc_sec_0000003499_000195004726005844', 'ALX: 144 filed 2026-06-09', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003499_000195004726005844', 'sec_0000003499', 'Form 144 — ALEXANDERS INC', 'ALEXANDERS INC (ALX). Form 144. Date 2026-06-09', 'candidate', '2026-06-09', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003499_000195004726005844', 'opp_sec_0000003499_000195004726005844', 'verified_fact', 'ALX: filed 144 on 2026-06-09', 0.9, '["ev_sec_0000003499_000195004726005844"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003499_000195004726005844', 'opp_sec_0000003499_000195004726005844', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003545_000000354526000036', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003545', '2026-07-17', NOW(), 'sec_0000003545_000000354526000036', 'Form 8-K — ALICO, INC.', 'ALICO, INC. (ALCO). Form 8-K. Date 2026-07-17', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003545_000000354526000036', 'doc_sec_0000003545_000000354526000036', 'ALCO: 8-K filed 2026-07-17', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003545_000000354526000036', 'sec_0000003545', 'Form 8-K — ALICO, INC.', 'ALICO, INC. (ALCO). Form 8-K. Date 2026-07-17', 'candidate', '2026-07-17', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003545_000000354526000036', 'opp_sec_0000003545_000000354526000036', 'verified_fact', 'ALCO: filed 8-K on 2026-07-17', 0.9, '["ev_sec_0000003545_000000354526000036"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003545_000000354526000036', 'opp_sec_0000003545_000000354526000036', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003570_000000357026000030', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003570', '2026-08-06', NOW(), 'sec_0000003570_000000357026000030', 'Form 8-K — Cheniere Energy, Inc.', 'Cheniere Energy, Inc. (LNG). Form 8-K. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003570_000000357026000030', 'doc_sec_0000003570_000000357026000030', 'LNG: 8-K filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003570_000000357026000030', 'sec_0000003570', 'Form 8-K — Cheniere Energy, Inc.', 'Cheniere Energy, Inc. (LNG). Form 8-K. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003570_000000357026000030', 'opp_sec_0000003570_000000357026000030', 'verified_fact', 'LNG: filed 8-K on 2026-08-06', 0.9, '["ev_sec_0000003570_000000357026000030"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003570_000000357026000030', 'opp_sec_0000003570_000000357026000030', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003570_000000357026000028', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003570', '2026-08-06', NOW(), 'sec_0000003570_000000357026000028', 'Form 10-Q — Cheniere Energy, Inc.', 'Cheniere Energy, Inc. (LNG). Form 10-Q. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003570_000000357026000028', 'doc_sec_0000003570_000000357026000028', 'LNG: 10-Q filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003570_000000357026000028', 'sec_0000003570', 'Form 10-Q — Cheniere Energy, Inc.', 'Cheniere Energy, Inc. (LNG). Form 10-Q. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003570_000000357026000028', 'opp_sec_0000003570_000000357026000028', 'verified_fact', 'LNG: filed 10-Q on 2026-08-06', 0.9, '["ev_sec_0000003570_000000357026000028"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003570_000000357026000028', 'opp_sec_0000003570_000000357026000028', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000003570_000000357026000025', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000003570', '2026-07-28', NOW(), 'sec_0000003570_000000357026000025', 'Form 8-K — Cheniere Energy, Inc.', 'Cheniere Energy, Inc. (LNG). Form 8-K. Date 2026-07-28', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000003570_000000357026000025', 'doc_sec_0000003570_000000357026000025', 'LNG: 8-K filed 2026-07-28', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000003570_000000357026000025', 'sec_0000003570', 'Form 8-K — Cheniere Energy, Inc.', 'Cheniere Energy, Inc. (LNG). Form 8-K. Date 2026-07-28', 'candidate', '2026-07-28', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000003570_000000357026000025', 'opp_sec_0000003570_000000357026000025', 'verified_fact', 'LNG: filed 8-K on 2026-07-28', 0.9, '["ev_sec_0000003570_000000357026000025"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000003570_000000357026000025', 'opp_sec_0000003570_000000357026000025', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004127_000110465926091968', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004127', '2026-08-06', NOW(), 'sec_0000004127_000110465926091968', 'Form 424B5 — SKYWORKS SOLUTIONS, INC.', 'SKYWORKS SOLUTIONS, INC. (SWKS). Form 424B5. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004127_000110465926091968', 'doc_sec_0000004127_000110465926091968', 'SWKS: 424B5 filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004127_000110465926091968', 'sec_0000004127', 'Form 424B5 — SKYWORKS SOLUTIONS, INC.', 'SKYWORKS SOLUTIONS, INC. (SWKS). Form 424B5. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004127_000110465926091968', 'opp_sec_0000004127_000110465926091968', 'verified_fact', 'SWKS: filed 424B5 on 2026-08-06', 0.9, '["ev_sec_0000004127_000110465926091968"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004127_000110465926091968', 'opp_sec_0000004127_000110465926091968', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004127_000110465926090490', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004127', '2026-08-04', NOW(), 'sec_0000004127_000110465926090490', 'Form FWP — SKYWORKS SOLUTIONS, INC.', 'SKYWORKS SOLUTIONS, INC. (SWKS). Form FWP. Date 2026-08-04', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004127_000110465926090490', 'doc_sec_0000004127_000110465926090490', 'SWKS: FWP filed 2026-08-04', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004127_000110465926090490', 'sec_0000004127', 'Form FWP — SKYWORKS SOLUTIONS, INC.', 'SKYWORKS SOLUTIONS, INC. (SWKS). Form FWP. Date 2026-08-04', 'candidate', '2026-08-04', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004127_000110465926090490', 'opp_sec_0000004127_000110465926090490', 'verified_fact', 'SWKS: filed FWP on 2026-08-04', 0.9, '["ev_sec_0000004127_000110465926090490"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004127_000110465926090490', 'opp_sec_0000004127_000110465926090490', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004127_000110465926089557', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004127', '2026-08-03', NOW(), 'sec_0000004127_000110465926089557', 'Form 424B5 — SKYWORKS SOLUTIONS, INC.', 'SKYWORKS SOLUTIONS, INC. (SWKS). Form 424B5. Date 2026-08-03', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004127_000110465926089557', 'doc_sec_0000004127_000110465926089557', 'SWKS: 424B5 filed 2026-08-03', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004127_000110465926089557', 'sec_0000004127', 'Form 424B5 — SKYWORKS SOLUTIONS, INC.', 'SKYWORKS SOLUTIONS, INC. (SWKS). Form 424B5. Date 2026-08-03', 'candidate', '2026-08-03', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004127_000110465926089557', 'opp_sec_0000004127_000110465926089557', 'verified_fact', 'SWKS: filed 424B5 on 2026-08-03', 0.9, '["ev_sec_0000004127_000110465926089557"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004127_000110465926089557', 'opp_sec_0000004127_000110465926089557', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004281_000110465926091610', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004281', '2026-08-06', NOW(), 'sec_0000004281_000110465926091610', 'Form 8-K — Howmet Aerospace Inc.', 'Howmet Aerospace Inc. (HWM). Form 8-K. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004281_000110465926091610', 'doc_sec_0000004281_000110465926091610', 'HWM: 8-K filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004281_000110465926091610', 'sec_0000004281', 'Form 8-K — Howmet Aerospace Inc.', 'Howmet Aerospace Inc. (HWM). Form 8-K. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004281_000110465926091610', 'opp_sec_0000004281_000110465926091610', 'verified_fact', 'HWM: filed 8-K on 2026-08-06', 0.9, '["ev_sec_0000004281_000110465926091610"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004281_000110465926091610', 'opp_sec_0000004281_000110465926091610', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004281_000000428126000025', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004281', '2026-08-06', NOW(), 'sec_0000004281_000000428126000025', 'Form 10-Q — Howmet Aerospace Inc.', 'Howmet Aerospace Inc. (HWM). Form 10-Q. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004281_000000428126000025', 'doc_sec_0000004281_000000428126000025', 'HWM: 10-Q filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004281_000000428126000025', 'sec_0000004281', 'Form 10-Q — Howmet Aerospace Inc.', 'Howmet Aerospace Inc. (HWM). Form 10-Q. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004281_000000428126000025', 'opp_sec_0000004281_000000428126000025', 'verified_fact', 'HWM: filed 10-Q on 2026-08-06', 0.9, '["ev_sec_0000004281_000000428126000025"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004281_000000428126000025', 'opp_sec_0000004281_000000428126000025', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004281_000001961726000282', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004281', '2026-07-22', NOW(), 'sec_0000004281_000001961726000282', 'Form SCHEDULE 13G/A — Howmet Aerospace Inc.', 'Howmet Aerospace Inc. (HWM). Form SCHEDULE 13G/A. Date 2026-07-22', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004281_000001961726000282', 'doc_sec_0000004281_000001961726000282', 'HWM: SCHEDULE 13G/A filed 2026-07-22', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004281_000001961726000282', 'sec_0000004281', 'Form SCHEDULE 13G/A — Howmet Aerospace Inc.', 'Howmet Aerospace Inc. (HWM). Form SCHEDULE 13G/A. Date 2026-07-22', 'candidate', '2026-07-22', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004281_000001961726000282', 'opp_sec_0000004281_000001961726000282', 'verified_fact', 'HWM: filed SCHEDULE 13G/A on 2026-07-22', 0.9, '["ev_sec_0000004281_000001961726000282"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004281_000001961726000282', 'opp_sec_0000004281_000001961726000282', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004457_000119312526335076', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004457', '2026-08-05', NOW(), 'sec_0000004457_000119312526335076', 'Form 8-K — U-Haul Holding Co /NV/', 'U-Haul Holding Co /NV/ (UHAL). Form 8-K. Date 2026-08-05', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004457_000119312526335076', 'doc_sec_0000004457_000119312526335076', 'UHAL: 8-K filed 2026-08-05', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004457_000119312526335076', 'sec_0000004457', 'Form 8-K — U-Haul Holding Co /NV/', 'U-Haul Holding Co /NV/ (UHAL). Form 8-K. Date 2026-08-05', 'candidate', '2026-08-05', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004457_000119312526335076', 'opp_sec_0000004457_000119312526335076', 'verified_fact', 'UHAL: filed 8-K on 2026-08-05', 0.9, '["ev_sec_0000004457_000119312526335076"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004457_000119312526335076', 'opp_sec_0000004457_000119312526335076', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004457_000119312526335008', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004457', '2026-08-05', NOW(), 'sec_0000004457_000119312526335008', 'Form 10-Q — U-Haul Holding Co /NV/', 'U-Haul Holding Co /NV/ (UHAL). Form 10-Q. Date 2026-08-05', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004457_000119312526335008', 'doc_sec_0000004457_000119312526335008', 'UHAL: 10-Q filed 2026-08-05', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004457_000119312526335008', 'sec_0000004457', 'Form 10-Q — U-Haul Holding Co /NV/', 'U-Haul Holding Co /NV/ (UHAL). Form 10-Q. Date 2026-08-05', 'candidate', '2026-08-05', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004457_000119312526335008', 'opp_sec_0000004457_000119312526335008', 'verified_fact', 'UHAL: filed 10-Q on 2026-08-05', 0.9, '["ev_sec_0000004457_000119312526335008"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004457_000119312526335008', 'opp_sec_0000004457_000119312526335008', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004457_000119312526292792', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004457', '2026-07-01', NOW(), 'sec_0000004457_000119312526292792', 'Form ARS — U-Haul Holding Co /NV/', 'U-Haul Holding Co /NV/ (UHAL). Form ARS. Date 2026-07-01', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004457_000119312526292792', 'doc_sec_0000004457_000119312526292792', 'UHAL: ARS filed 2026-07-01', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004457_000119312526292792', 'sec_0000004457', 'Form ARS — U-Haul Holding Co /NV/', 'U-Haul Holding Co /NV/ (UHAL). Form ARS. Date 2026-07-01', 'candidate', '2026-07-01', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004457_000119312526292792', 'opp_sec_0000004457_000119312526292792', 'verified_fact', 'UHAL: filed ARS on 2026-07-01', 0.9, '["ev_sec_0000004457_000119312526292792"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004457_000119312526292792', 'opp_sec_0000004457_000119312526292792', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004962_000110465926092092', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004962', '2026-08-06', NOW(), 'sec_0000004962_000110465926092092', 'Form 424B2 — AMERICAN EXPRESS CO', 'AMERICAN EXPRESS CO (AXP). Form 424B2. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004962_000110465926092092', 'doc_sec_0000004962_000110465926092092', 'AXP: 424B2 filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004962_000110465926092092', 'sec_0000004962', 'Form 424B2 — AMERICAN EXPRESS CO', 'AMERICAN EXPRESS CO (AXP). Form 424B2. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004962_000110465926092092', 'opp_sec_0000004962_000110465926092092', 'verified_fact', 'AXP: filed 424B2 on 2026-08-06', 0.9, '["ev_sec_0000004962_000110465926092092"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004962_000110465926092092', 'opp_sec_0000004962_000110465926092092', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004962_000110465926091274', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004962', '2026-08-05', NOW(), 'sec_0000004962_000110465926091274', 'Form FWP — AMERICAN EXPRESS CO', 'AMERICAN EXPRESS CO (AXP). Form FWP. Date 2026-08-05', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004962_000110465926091274', 'doc_sec_0000004962_000110465926091274', 'AXP: FWP filed 2026-08-05', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004962_000110465926091274', 'sec_0000004962', 'Form FWP — AMERICAN EXPRESS CO', 'AMERICAN EXPRESS CO (AXP). Form FWP. Date 2026-08-05', 'candidate', '2026-08-05', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004962_000110465926091274', 'opp_sec_0000004962_000110465926091274', 'verified_fact', 'AXP: filed FWP on 2026-08-05', 0.9, '["ev_sec_0000004962_000110465926091274"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004962_000110465926091274', 'opp_sec_0000004962_000110465926091274', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004962_000000496226000327', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004962', '2026-08-05', NOW(), 'sec_0000004962_000000496226000327', 'Form 8-K — AMERICAN EXPRESS CO', 'AMERICAN EXPRESS CO (AXP). Form 8-K. Date 2026-08-05', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004962_000000496226000327', 'doc_sec_0000004962_000000496226000327', 'AXP: 8-K filed 2026-08-05', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004962_000000496226000327', 'sec_0000004962', 'Form 8-K — AMERICAN EXPRESS CO', 'AMERICAN EXPRESS CO (AXP). Form 8-K. Date 2026-08-05', 'candidate', '2026-08-05', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004962_000000496226000327', 'opp_sec_0000004962_000000496226000327', 'verified_fact', 'AXP: filed 8-K on 2026-08-05', 0.9, '["ev_sec_0000004962_000000496226000327"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004962_000000496226000327', 'opp_sec_0000004962_000000496226000327', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004977_000162828026054333', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004977', '2026-08-06', NOW(), 'sec_0000004977_000162828026054333', 'Form 8-K — AFLAC INC', 'AFLAC INC (AFL). Form 8-K. Date 2026-08-06', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004977_000162828026054333', 'doc_sec_0000004977_000162828026054333', 'AFL: 8-K filed 2026-08-06', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004977_000162828026054333', 'sec_0000004977', 'Form 8-K — AFLAC INC', 'AFLAC INC (AFL). Form 8-K. Date 2026-08-06', 'candidate', '2026-08-06', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004977_000162828026054333', 'opp_sec_0000004977_000162828026054333', 'verified_fact', 'AFL: filed 8-K on 2026-08-06', 0.9, '["ev_sec_0000004977_000162828026054333"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004977_000162828026054333', 'opp_sec_0000004977_000162828026054333', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000004977_000162828026046124', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000004977', '2026-06-30', NOW(), 'sec_0000004977_000162828026046124', 'Form 8-K — AFLAC INC', 'AFLAC INC (AFL). Form 8-K. Date 2026-06-30', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000004977_000162828026046124', 'doc_sec_0000004977_000162828026046124', 'AFL: 8-K filed 2026-06-30', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000004977_000162828026046124', 'sec_0000004977', 'Form 8-K — AFLAC INC', 'AFLAC INC (AFL). Form 8-K. Date 2026-06-30', 'candidate', '2026-06-30', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000004977_000162828026046124', 'opp_sec_0000004977_000162828026046124', 'verified_fact', 'AFL: filed 8-K on 2026-06-30', 0.9, '["ev_sec_0000004977_000162828026046124"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000004977_000162828026046124', 'opp_sec_0000004977_000162828026046124', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000005094_000000509426000023', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000005094', '2026-07-29', NOW(), 'sec_0000005094_000000509426000023', 'Form NPORT-P — Invesco Bond Fund', 'Invesco Bond Fund (VBF). Form NPORT-P. Date 2026-07-29', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000005094_000000509426000023', 'doc_sec_0000005094_000000509426000023', 'VBF: NPORT-P filed 2026-07-29', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000005094_000000509426000023', 'sec_0000005094', 'Form NPORT-P — Invesco Bond Fund', 'Invesco Bond Fund (VBF). Form NPORT-P. Date 2026-07-29', 'candidate', '2026-07-29', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000005094_000000509426000023', 'opp_sec_0000005094_000000509426000023', 'verified_fact', 'VBF: filed NPORT-P on 2026-07-29', 0.9, '["ev_sec_0000005094_000000509426000023"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000005094_000000509426000023', 'opp_sec_0000005094_000000509426000023', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000005094_000119312526292860', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000005094', '2026-07-02', NOW(), 'sec_0000005094_000119312526292860', 'Form DEFA14A — Invesco Bond Fund', 'Invesco Bond Fund (VBF). Form DEFA14A. Date 2026-07-02', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000005094_000119312526292860', 'doc_sec_0000005094_000119312526292860', 'VBF: DEFA14A filed 2026-07-02', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000005094_000119312526292860', 'sec_0000005094', 'Form DEFA14A — Invesco Bond Fund', 'Invesco Bond Fund (VBF). Form DEFA14A. Date 2026-07-02', 'candidate', '2026-07-02', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000005094_000119312526292860', 'opp_sec_0000005094_000119312526292860', 'verified_fact', 'VBF: filed DEFA14A on 2026-07-02', 0.9, '["ev_sec_0000005094_000119312526292860"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000005094_000119312526292860', 'opp_sec_0000005094_000119312526292860', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, source_id, canonical_url, published_at, retrieved_at, content_hash, title, text, created_at)
VALUES ('doc_sec_0000005094_000119312526271417', 'source_sec_edgar', 'https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000005094', '2026-06-16', NOW(), 'sec_0000005094_000119312526271417', 'Form DEF 14A — Invesco Bond Fund', 'Invesco Bond Fund (VBF). Form DEF 14A. Date 2026-06-16', NOW())
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO evidence_items (id, document_id, excerpt, evidence_type, quality_score, created_at)
VALUES ('ev_sec_0000005094_000119312526271417', 'doc_sec_0000005094_000119312526271417', 'VBF: DEF 14A filed 2026-06-16', 'primary', 88, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO opportunities (id, security_id, title, summary, status, detected_at, created_at, updated_at)
VALUES ('opp_sec_0000005094_000119312526271417', 'sec_0000005094', 'Form DEF 14A — Invesco Bond Fund', 'Invesco Bond Fund (VBF). Form DEF 14A. Date 2026-06-16', 'candidate', '2026-06-16', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO claims (id, opportunity_id, claim_type, text, confidence, evidence_item_ids, created_at)
VALUES ('claim_sec_0000005094_000119312526271417', 'opp_sec_0000005094_000119312526271417', 'verified_fact', 'VBF: filed DEF 14A on 2026-06-16', 0.9, '["ev_sec_0000005094_000119312526271417"]', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (id, opportunity_id, score_type, value, factors, model_version, calculated_at)
VALUES ('score_sec_0000005094_000119312526271417', 'opp_sec_0000005094_000119312526271417', 'opportunity', 70, '{}', '1.0.0', NOW())
ON CONFLICT (id) DO NOTHING;

-- Auto-publish opportunities with evidence quality >= 80
UPDATE opportunities SET status = 'published', published_at = NOW()
WHERE status = 'candidate' AND id IN (
  SELECT o.id FROM opportunities o
  JOIN claims c ON c.opportunity_id = o.id
  WHERE o.status = 'candidate' AND c.claim_type = 'verified_fact'
  GROUP BY o.id HAVING COUNT(c.id) >= 1
);

-- Stats
SELECT status, COUNT(*) FROM opportunities GROUP BY status;
